[package]

name = "conduit-middleware"
version = "0.9.0-alpha.4"
authors = ["wycats@gmail.com",
           "Alex Crichton <alex@alexcrichton.com>"]
description = "HTTP Middleware interface using the conduit interface"
repository = "https://github.com/conduit-rust/conduit-middleware"
license = "MIT"
edition = "2018"

[dependencies]
conduit = "0.9.0-alpha.5"

[dev-dependencies]
conduit-test = "0.9.0-alpha.5"
