name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: cargo doc --no-deps
